site_name: Vincent's Tech Blog

nav:
  - index.md
  - Blog:
      - blog/index.md

theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.indexes

plugins:
  - blog:
      blog_toc: true


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences